services:
  dobot:
    build:
      context: ./dobot
    volumes:
      - ../app/src/:/app/
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - dobot_network
    ports:
      - "29999:29999"
      - "30003:30003"
      - "30004:30004"
      - "30005:30005"
      - "30006:30006"

networks:
  dobot_network:
    name: dobot_network
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.10.0.0/24
